### ISSUE TITLE
Run in custom dataset

### ISSUE THREAD

**Issue by wangerxiao001** [facebookresearch/unbiased-teacher#13]
Hello! I want to run this code on my own coco-style dataset. But I don't know how to create the dataseed like the file [COCO_supervision.txt](https://github.com/facebookresearch/unbiased-teacher/blob/main/dataseed/COCO_supervision.txt) in your project. Looking forward to your answer! Was that the image ID in the original COCO dataset or the self-created image id of you?

**Comment by wangerxiao001** [comment]
Got it at [here](https://github.com/facebookresearch/unbiased-teacher/blob/ba543ed2b87446c79eaf41f93320de246c8eedc2/ubteacher/data/build.py#L51). It's your self-created ID.

**Comment by ycliu93** [comment]
Yes, you could check issue #8  for more details
