### ISSUE TITLE
using  randon select date get more higher result than using COCO_supervision.txt

### ISSUE THREAD

**Issue by happyxuwork** [facebookresearch/unbiased-teacher#14]
by using the COCO_supervision.txt config when using the 10% coco as the label dataset,the results are reproducible, but when i change to the seting of random select data just as https://github.com/facebookresearch/unbiased-teacher/issues/8#issuecomment-808687654, i get more higher result:AP:36.489, under the 10% coco as the label dataset

**Comment by happyxuwork** [comment]
@ycliu93  do you have some Suggestions ？This is weird.  when using 10% coco lable data accroding COCO_supervision.txt, can get AP :31.39, but random selecting can get AP:36.489, and i calculated the distribution of instances when using random, almost same as the COCO_supervision.txt,just as fellow
![diff](https://user-images.githubusercontent.com/26646071/115236463-fa5ec280-a14d-11eb-999e-65bb512825d4.png)

**Comment by ycliu93** [comment]
Did you use multiple GPUs? It is likely that each GPU samples different 10% data? Could you check whether all GPUs sample the same random list?

**Comment by happyxuwork** [comment]
just as your said, i used multiple GPUs, and each GPU samples different 10% data, so get higher resuler.  so i fiexd the seed by using np.random.seed(1), keep the  each GPU samples same 10% data. thanks
