### ISSUE TITLE
Minor implementation issue in data loader

### ISSUE THREAD

**Issue by vlfom** [facebookresearch/unbiased-teacher#18]
Thanks a lot for releasing the code publicly, it is very helpful and clean.

I have a small doubt about implementation of the data loader, specifically, [this portion of code](https://github.com/facebookresearch/unbiased-teacher/blob/main/ubteacher/data/common.py#L127): 

<img src="https://user-images.githubusercontent.com/5049284/116745840-5ce47800-aa04-11eb-81a1-fb34b23acfc6.png" width="500" />

It seems to me that because the batches for labeled and unlabeled images are filled separately, sooner or later some images will be skipped.

Of course, there exist theoretical worst cases where half of the images in both datasets would be skipped, but in reality, when the ratios of images are balanced, this probably has a negligible impact on experiments (?).
Just wanted to bring this up or please let me know if I'm wrong.

[One idea](https://github.com/vlfom/CSD-detectron2/blob/master/csd/data/build.py#L133) to properly implement this is to use two separate iterators that lazily fetch images from datasets individually.

**Comment by ycliu93** [comment]
Thanks @vlfom! That's indeed a better way to iterate labeled and unlabeled data!
