### ISSUE TITLE
Please upload Model Zoo quickly,I can't wait to learn your work

### ISSUE THREAD

**Issue by NARRZ** [facebookresearch/unbiased-teacher#2]
Please,thank you very much!

**Comment by ycliu93** [comment]
Thanks for your interest. We will upload these model weights as soon as possible.

**Comment by Zumbalamambo** [comment]
+1

**Comment by rammyram** [comment]
+1

**Comment by ycliu93** [comment]
Hi, the model weights are uploaded.

**Comment by fedyhajali** [comment]
Hi @ycliu93, I would like to ask you where I could find the model weights for the COCO-Additional experiment since they are not present in the Readme tables.
