### ISSUE TITLE
how to get labeled data in coco-standard

### ISSUE THREAD

**Issue by namihagi** [facebookresearch/unbiased-teacher#21]
Thank you for your work, and I have a question about random labeled data in coco-standard setting.
Is labeled data is randomly sampled in the same class, or from all classes?
if it is sampled from all classes, I think that labeled data has class imbalance.

**Comment by ycliu93** [comment]
The experimental setting in this implementation and paper is to sample from all classes. So the labeled data indeed has an imbalance problem. Even though you uniformly sample from each class in the **training set**, there is still a **class-imbalance** issue in the testing set.

If you are interested in this scenario, there are some papers like [1] discussing a similar problem but not specifically for object detection. 
[1] "Posterior Re-calibration for Imbalanced Datasets", Tian et al., NeurIPS 2020
