### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by xiaohui0225** [facebookresearch/unbiased-teacher#24]
Dear author, hello. What does the code shown below mean? Why is there "instances" and what does it mean? thanks！

        if "instances" in batched_inputs[0]:
            gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
        else:
            gt_instances = None

TypeError: 'NoneType' object is not iterable

**Comment by ycliu93** [comment]
**Why is there "instances" and what does it mean?**
A: Each element of batch_inputs contains an image and a label (ground-truth label for labeled data or pseudo-label for unlabeled data).

**What causes the error you encountered?** 
A: It seems that your `batched_inputs`  is `None`, and this makes the `batched_inputs` not iterable (`batched_inputs[0]` causes the error.)
