### ISSUE TITLE
question: double evaluation during training

### ISSUE THREAD

**Issue by hachreak** [facebookresearch/unbiased-teacher#25]
Hi everybody,
on test every `EVAL_PERIOD` iterations start a evaluation.
Inside the logs I see that it runs 2 times.
Is the first for the teacher model and the second for the student model? Or viceversa?
Where do you run the evaluation inside the code? 
Thanks a lot.

**Comment by ycliu93** [comment]
Hi @hachreak ,

Yes, the evaluation runs twice. The first one is for student, and the second one is for teacher.

https://github.com/facebookresearch/unbiased-teacher/blob/ba543ed2b87446c79eaf41f93320de246c8eedc2/ubteacher/engine/trainer.py#L618-L619

This is where we do the evaluations, and we follow the default evaluation function in Detectron2.
Thanks!
