### ISSUE TITLE
About VOC dataset training settings.

### ISSUE THREAD

**Issue by xpyqiubai** [facebookresearch/unbiased-teacher#26]
Thanks a lot to the author for open sourcing the unbiased-teacher code. However, only the training configuration file (.yaml) on the coco dataset is provided in the code. I sincerely hope the authors will share the training configuration file (.yaml) on the VOC dataset. Thanks again to the authors.

With best regards

**Comment by ycliu93** [comment]
Hi @xpyqiubai , sorry for late reply. 

I uploaded all configs and weights for VOC experiments
