### ISSUE TITLE
I want to make sure I'm right about what I know

### ISSUE THREAD

**Issue by yeonsikch** [facebookresearch/unbiased-teacher#28]
Hi, Thanks for your paper and code.

i want to make sure i'm right about what i know.
plz, tell me answer about this questions.

1. is it right that use 2k iters about all {1,5,10,20}% labels in  burn-in stage?
2. when i use batch size = (label = 12, unlabel = 12), it is batch size = 12(only labeled data) in Burn-in stage. Then,  it is batch size = (12, 12)(labeled data, unlabeled data) in Student Model. is it right?
3. In training log, i can see continuous two AP tables. what diff for two tables?

Thanks!

**Comment by ycliu93** [comment]
1. Yes, all degrees of supervision use 2k iterations for the burn-in stage.
2. Yes, batch sizes of the labeled set are the same across the burn-in stage and mutual-learning stage and are set by `SOLVER.IMG_PER_BATCH_LABEL`.
3.  First AP table is for the student model, and the second AP table is for the teacher model.

Thanks

**Comment by yeonsikch** [comment]
Thanks for ur answer. So thanks.

may i some question to u?

then, when i want to supervised learning for {1%, 5%, 20% ... etc}learning, i have to use other code? not in this code?
i think that fisrt AP block is supervised learning.

**Comment by ycliu93** [comment]
The burn-in stage is basically the supervised learning of the student model, so you could extend the training iterations (from 3k to 90k/180k) of the burn-in stage for the supervised training (labeled data only).

**Comment by yeonsikch** [comment]
Thank u so much! This is very helpful to me.
Finally i have a just one question.

While burn-in stage(=student model), this model = "normal Faster R-CNN". is right?

I want  compare Supervised Learning and Semi-Supervised Learning.

Thanks.
