### ISSUE TITLE
Performance is evaluated on the Teacher model？  

### ISSUE THREAD

**Issue by sisrfeng** [facebookresearch/unbiased-teacher#3]
Performance is evaluated on the Teacher model？Not Student？
![image](https://user-images.githubusercontent.com/53520949/110886198-3dde3980-8323-11eb-816d-ee9fe970b328.png)

Should 2k iteration be actually 20k? 
![image](https://user-images.githubusercontent.com/53520949/110886148-2606b580-8323-11eb-9f0f-1967d697a37f.png)

Thx~

**Comment by ycliu93** [comment]
Yes, the performance is evaluated on the teacher model, and the student model usually performs 1~2 mAP lower. For the burn-in stage, we only trained 2k iterations. 

Thanks.
