### ISSUE TITLE
Augmentation?

### ISSUE THREAD

**Issue by jiangzhengkai** [facebookresearch/unbiased-teacher#30]
Hi, where is the augmentation implemeted? I could not find the weak aug and strong aug.

**Comment by ycliu93** [comment]
This is where we implemented strong augmentation.

https://github.com/facebookresearch/unbiased-teacher/blob/6977c6f77c812fae4064dc1b3865658c2ed247b1/ubteacher/data/detection_utils.py#L9-L46

For the weak augmentation, we only use horizontal random flip.
https://github.com/facebookresearch/unbiased-teacher/blob/6977c6f77c812fae4064dc1b3865658c2ed247b1/ubteacher/data/dataset_mapper.py#L92-L94

Thanks

**Comment by ycliu93** [comment]
I will close this issue as there is no other question. Welcome to reopen if you have other relevant questions.
