### ISSUE TITLE
Visualize the pseudo-labels

### ISSUE THREAD

**Issue by ogamache** [facebookresearch/unbiased-teacher#34]
Hello! Thanks for your great work, it is really nice.

I was wondering, is it possible to visualize the job done by the Student to assign pseudo-labels to the images while running the training? My goal is to see the Student improves directly on the images from the dataset! (by example, see the bounding boxes around the objects and notice that the evaluation is better and better when the iterations increase)

Thank you for your help!

**Comment by ycliu93** [comment]
My suggestion is to add the `visualize_training`(a function under `GeneralizedRCNN` class) to the output of student's prediction output in `TwoStagePseudoLabGeneralizedRCNN` (`rcnn.py`).


Here is the reference:

https://github.com/facebookresearch/unbiased-teacher/blob/6977c6f77c812fae4064dc1b3865658c2ed247b1/ubteacher/modeling/meta_arch/rcnn.py#L7

`visualize_training` function in class `GeneralizedRCNN` is defined in this link:
https://github.com/facebookresearch/detectron2/blob/9eb0027d795bb9a38098bb05e2ceb273bfc9cf41/detectron2/modeling/meta_arch/rcnn.py#L87

Thanks

**Comment by ogamache** [comment]
Thanks for the quick answer! I tried your idea and it works fine while I am in the "supervised" branch, since the batch contains the ground truth information for each images. But when I am trying to use the `visualize_training` function in the "unsup_data_weak" branch, it doesn't work since the images in the batch have no annotation..!

Do you have an idea how to get over this problem?

**Comment by ogamache** [comment]
Thanks for the tip! It works fine with some slight modifications :)

**Comment by Fly-dream12** [comment]
Can you explain how you make these modifications ? Is this should only be visualized in the training phase ?
How can i visualize using a trained model? Thanks! @ogamache @ycliu93
