### ISSUE TITLE
COCOEval on Pascal dataset experiments

### ISSUE THREAD

**Issue by JongMokKim** [facebookresearch/unbiased-teacher#40]
Hi,

I saw your README.MD that there is an higher AP issue when using voc_evaluator than coco_evaluator.

I just want to reproduce your results of paper, so I want to train voc data and evaluate network on coco_evaluator

I used your config script that includes EVALUATOR : COCOEVAL, but it seems voc evaluator ran, not coco evaluator.

Could you share your way?

**Comment by ycliu93** [comment]
Sorry, the `EVALUATOR`  in config file is deprecated. If you would like to change the evaluator to the original evaluator.

Please change this line   
https://github.com/facebookresearch/unbiased-teacher/blob/6977c6f77c812fae4064dc1b3865658c2ed247b1/ubteacher/engine/trainer.py#L166

to 
```
return COCOEvaluator(dataset_name, output_dir=output_folder)
```

In this way, you are able to use the COCO evaluator.
