### ISSUE TITLE
Implementation of CSD

### ISSUE THREAD

**Issue by wjn922** [facebookresearch/unbiased-teacher#42]
Hi,

Thanks for the solid work. Could you also provide the code of CSD implementation? Thanks.

**Comment by ycliu93** [comment]
Thanks for the interest. 

We don't plan to release the code of CSD implementation, while I could provide the suggestion to reproduce this baseline.
You could simply follow the original implementation of CSD for two-stage detectors and adapt to this codebase.
https://github.com/soo89/CSD-RFCN
