### ISSUE TITLE
How to evaluate the performance of labeled data?

### ISSUE THREAD

**Issue by wjn922** [facebookresearch/unbiased-teacher#43]
Hi,

How to train the supervised model by only using 1% / 2% / 5% / 10% data?

Further question:
How to train using the coco-additional (100% coco + unlabeled data)

**Comment by ycliu93** [comment]
Since our burn-in stage is actually the vanilla supervised training.
You could extend the burn-in stage iterations, and that is the supervised-only baseline with the labeled set only (1%-10%).
And, don't forget to add the learning rate decay back for the supervised baseline for a fair comparison.
