### ISSUE TITLE
Question about burn-in steps

### ISSUE THREAD

**Issue by Chrisfsj2051** [facebookresearch/unbiased-teacher#6]
Hi! It's exciting to see such work with remarkable improvements. 

However, I have a question about the setting of the burn-in steps. In the paper, you mentioned that different step values are set for different data settings (e.g. 20k for COCO@10%). But it seems like that you set steps to 2000 in all configs, what is the reason?

**Comment by Chrisfsj2051** [comment]
Besides, what is the value of burn-in steps that you used in VOC experiments?

**Comment by ycliu93** [comment]
Hi @Chrisfsj2051,


1. We found out using 20k or 2k iterations for burn-in could converge to a similar mAP at the end of the training. 
2. For the burn-in steps, we use 30k iterations.

Thanks!
