### ISSUE TITLE
Nan appears when training

### ISSUE THREAD

**Issue by happyxuwork** [facebookresearch/unbiased-teacher#7]
i set use the default seting as the github, run python train_net.py --num-gpus 8 --config configs/coco_supervision/faster_rcnn_R_50_FPN_sup10_run1.yaml SOLVER.IMG_PER_BATCH_LABEL 16 SOLVER.IMG_PER_BATCH_UNLABEL 16; but from 19 steps ,The following information appears.
![20210326-092159(WeLinkPC)](https://user-images.githubusercontent.com/26646071/112565056-5a946a00-8e17-11eb-895d-baa0f3de12f5.png)
 is normal？ is any config should altert?   Looking forward to your reply！

**Comment by ycliu93** [comment]
It is not normal for having Nan loss in the training. Could you try to reduce the unsupervised loss weight to 2 and see if the model still cannot converge?

**Comment by happyxuwork** [comment]
> It is not normal for having Nan loss in the training. Could you try to reduce the unsupervised loss weight to 2 and see if the model still cannot converge?

by altering the learning rate from  0.01 to 0.001,  not Nan appears. so the default seting of learning rate in https://github.com/facebookresearch/unbiased-teacher/blob/05dad84c8e1bb44c6fd14706571ab0769143e48d/configs/coco_supervision/faster_rcnn_R_50_FPN_sup05_run1.yaml#L22  need to be modified to 0.001?

**Comment by ycliu93** [comment]
I would suggest reducing the unsupervised loss weight to 2 first and see if nan loss won't appear. Reducing the learning rate might affect the final performance.

**Comment by Fly-dream12** [comment]
When training the model on custom dataset, the learning rate is set as 0.001 and ims_per_batch_label is set as 4, this error happens in ubteacher/modeling/proposal_generator/proposal_utils.py in find_top_rpn_proposals:
FloatingPointError: Predicted boxes or scores contain Inf/Nan. Training has diverged.

is any config should be altered? Thanks for your apply! @ ycliu93 @happyxuwork
