### ISSUE TITLE
Supervised Loss for Student

### ISSUE THREAD

**Issue by michaelku1** [facebookresearch/unbiased-teacher#72]
Hello @ycliu93, Thanks for your work.

I'd just like to confirm whether the student model actually uses the labelled data as part of training along with the pseudo-labelled data. This is because in the paper the diagram only shows strongly augmented data passed into the student model, but in the code  there is a forward pass for the student model that also takes labelled data with both weak and strong augmentations. For your references:

This shows that weakly augmented unlabelled data is for the teacher branch.
<img width="783" alt="Screenshot 2022-03-04 at 00 06 47" src="https://user-images.githubusercontent.com/48415065/156604098-fffc2934-7032-4647-b9e1-697ab9e1fd13.png">

This shows that Lsup is from burn-in, and Lunsup is from the supervision of pseudo-labels.
<img width="670" alt="Screenshot 2022-03-04 at 00 07 46" src="https://user-images.githubusercontent.com/48415065/156603875-8ebe65c0-d6ae-4d96-9d41-f4305186b2d4.png">

This shows that student model has a forward pass given the labelled data (in which the forward pass is not for the burn-in)
<img width="481" alt="Screenshot 2022-03-04 at 00 05 56" src="https://user-images.githubusercontent.com/48415065/156603581-4f068b32-b5af-4adb-a5a4-56db2697a53b.png">

Thanks very much.

**Comment by ycliu93** [comment]
Thanks for asking. Yes, we input both weak and strong into the student model in the code.
And we also tried to only use strong-augmented images, and we got similar results.

**Comment by michaelku1** [comment]
Thanks, that answered my question.
